{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jahez-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
    {{- if .Values.ingress.certificateArn }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificateArn }}
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    {{- else }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    {{- end }}
spec:
  rules:
    - {{ if .Values.ingress.host }}host: {{ .Values.ingress.host }}
      {{ end }}http:
        paths:
          {{- range $name, $svc := .Values.services }}
          {{- if $svc.public }}
          - path: {{ $svc.path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}
                port:
                  number: {{ $svc.port }}
          {{- end }}
          {{- end }}
{{- end }}
